//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morpher.WebService.V3.MorpherSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://morpher.ru/", ConfigurationName="MorpherSoap.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetAdjectivesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse GetAdjectives(Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectives", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse> GetAdjectivesAsync(Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest request);
        
        // CODEGEN: Generating message contract since message GetAdjectiveGendersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectiveGenders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse GetAdjectiveGenders(Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectiveGenders", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse> GetAdjectiveGendersAsync(Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest request);
        
        // CODEGEN: Generating message contract since message SubmitCorrectionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/SubmitCorrection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse SubmitCorrection(Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/SubmitCorrection", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse> SubmitCorrectionAsync(Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest request);
        
        // CODEGEN: Generating message contract since message GetAccountStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse GetAccountStatus(Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAccountStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse> GetAccountStatusAsync(Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetDeclensionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDeclension", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse GetDeclension(Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDeclension", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse> GetDeclensionAsync(Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest request);
        
        // CODEGEN: Generating message contract since message GetXmlUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXmlUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse GetXmlUkr(Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXmlUkr", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse> GetXmlUkrAsync(Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest request);
        
        // CODEGEN: Generating message contract since message PropisUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/PropisUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.PropisUkrResponse PropisUkr(Morpher.WebService.V3.MorpherSoap.PropisUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/PropisUkr", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisUkrResponse> PropisUkrAsync(Morpher.WebService.V3.MorpherSoap.PropisUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDailyQueryLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDailyQueryLimit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDailyQueryLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDailyQueryLimitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/ValidateClientID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateClientID(string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/ValidateClientID", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidateClientIDAsync(string clientID);
        
        // CODEGEN: Generating message contract since message GetXmlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.GetXmlResponse GetXml(Morpher.WebService.V3.MorpherSoap.GetXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXml", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlResponse> GetXmlAsync(Morpher.WebService.V3.MorpherSoap.GetXmlRequest request);
        
        // CODEGEN: Generating message contract since message PropisRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/Propis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.WebService.V3.MorpherSoap.PropisResponse Propis(Morpher.WebService.V3.MorpherSoap.PropisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/Propis", ReplyAction="*")]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisResponse> PropisAsync(Morpher.WebService.V3.MorpherSoap.PropisRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Forms nField;
        
        private Forms unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Forms n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Forms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string иField;
        
        private string рField;
        
        private string дField;
        
        private string вField;
        
        private string тField;
        
        private string пField;
        
        private string поField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
                this.RaisePropertyChanged("И");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string В {
            get {
                return this.вField;
            }
            set {
                this.вField = value;
                this.RaisePropertyChanged("В");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Т {
            get {
                return this.тField;
            }
            set {
                this.тField = value;
                this.RaisePropertyChanged("Т");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string П {
            get {
                return this.пField;
            }
            set {
                this.пField = value;
                this.RaisePropertyChanged("П");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("П-о", Order=6)]
        public string По {
            get {
                return this.поField;
            }
            set {
                this.поField = value;
                this.RaisePropertyChanged("По");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlResult : Forms {
        
        private string родField;
        
        private Forms множественноеField;
        
        private string гдеField;
        
        private string кудаField;
        
        private string откудаField;
        
        private ФИО фИОField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string род {
            get {
                return this.родField;
            }
            set {
                this.родField = value;
                this.RaisePropertyChanged("род");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множественное {
            get {
                return this.множественноеField;
            }
            set {
                this.множественноеField = value;
                this.RaisePropertyChanged("множественное");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string где {
            get {
                return this.гдеField;
            }
            set {
                this.гдеField = value;
                this.RaisePropertyChanged("где");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string куда {
            get {
                return this.кудаField;
            }
            set {
                this.кудаField = value;
                this.RaisePropertyChanged("куда");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string откуда {
            get {
                return this.откудаField;
            }
            set {
                this.откудаField = value;
                this.RaisePropertyChanged("откуда");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
                this.RaisePropertyChanged("ФИО");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class ФИО : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string фField;
        
        private string иField;
        
        private string оField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ф {
            get {
                return this.фField;
            }
            set {
                this.фField = value;
                this.RaisePropertyChanged("Ф");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
                this.RaisePropertyChanged("И");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
                this.RaisePropertyChanged("О");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisUkrResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormsUkr nField;
        
        private FormsUkr unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormsUkr n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormsUkr unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlUkrResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class FormsUkr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string нField;
        
        private string рField;
        
        private string дField;
        
        private string зField;
        
        private string оField;
        
        private string мField;
        
        private string кField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Н {
            get {
                return this.нField;
            }
            set {
                this.нField = value;
                this.RaisePropertyChanged("Н");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string З {
            get {
                return this.зField;
            }
            set {
                this.зField = value;
                this.RaisePropertyChanged("З");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
                this.RaisePropertyChanged("О");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string М {
            get {
                return this.мField;
            }
            set {
                this.мField = value;
                this.RaisePropertyChanged("М");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string К {
            get {
                return this.кField;
            }
            set {
                this.кField = value;
                this.RaisePropertyChanged("К");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlUkrResult : FormsUkr {
        
        private string рідField;
        
        private Forms множинаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string рід {
            get {
                return this.рідField;
            }
            set {
                this.рідField = value;
                this.RaisePropertyChanged("рід");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множина {
            get {
                return this.множинаField;
            }
            set {
                this.множинаField = value;
                this.RaisePropertyChanged("множина");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class AdjectiveGenders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feminineField;
        
        private string neuterField;
        
        private string pluralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feminine {
            get {
                return this.feminineField;
            }
            set {
                this.feminineField = value;
                this.RaisePropertyChanged("feminine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string neuter {
            get {
                return this.neuterField;
            }
            set {
                this.neuterField = value;
                this.RaisePropertyChanged("neuter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string plural {
            get {
                return this.pluralField;
            }
            set {
                this.pluralField = value;
                this.RaisePropertyChanged("plural");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectives", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectivesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetAdjectivesRequest() {
        }
        
        public GetAdjectivesRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectivesResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectivesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string[] GetAdjectivesResult;
        
        public GetAdjectivesResponse() {
        }
        
        public GetAdjectivesResponse(string[] GetAdjectivesResult) {
            this.GetAdjectivesResult = GetAdjectivesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectiveGenders", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectiveGendersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetAdjectiveGendersRequest() {
        }
        
        public GetAdjectiveGendersRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectiveGendersResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectiveGendersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.AdjectiveGenders GetAdjectiveGendersResult;
        
        public GetAdjectiveGendersResponse() {
        }
        
        public GetAdjectiveGendersResponse(Morpher.WebService.V3.MorpherSoap.AdjectiveGenders GetAdjectiveGendersResult) {
            this.GetAdjectiveGendersResult = GetAdjectiveGendersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrection", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class SubmitCorrectionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.GetXmlResult correction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string comment;
        
        public SubmitCorrectionRequest() {
        }
        
        public SubmitCorrectionRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, Morpher.WebService.V3.MorpherSoap.GetXmlResult correction, string comment) {
            this.Credentials = Credentials;
            this.correction = correction;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrectionResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class SubmitCorrectionResponse {
        
        public SubmitCorrectionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatus", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAccountStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        public GetAccountStatusRequest() {
        }
        
        public GetAccountStatusRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials) {
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatusResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAccountStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string GetAccountStatusResult;
        
        public GetAccountStatusResponse() {
        }
        
        public GetAccountStatusResponse(string GetAccountStatusResult) {
            this.GetAccountStatusResult = GetAccountStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeclension", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetDeclensionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetDeclensionRequest() {
        }
        
        public GetDeclensionRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeclensionResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetDeclensionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.GetXmlResult GetDeclensionResult;
        
        public GetDeclensionResponse() {
        }
        
        public GetDeclensionResponse(Morpher.WebService.V3.MorpherSoap.GetXmlResult GetDeclensionResult) {
            this.GetDeclensionResult = GetDeclensionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlUkrRequest() {
        }
        
        public GetXmlUkrRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.GetXmlUkrResult GetXmlUkrResult;
        
        public GetXmlUkrResponse() {
        }
        
        public GetXmlUkrResponse(Morpher.WebService.V3.MorpherSoap.GetXmlUkrResult GetXmlUkrResult) {
            this.GetXmlUkrResult = GetXmlUkrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisUkrRequest() {
        }
        
        public PropisUkrRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.PropisUkrResult PropisUkrResult;
        
        public PropisUkrResponse() {
        }
        
        public PropisUkrResponse(Morpher.WebService.V3.MorpherSoap.PropisUkrResult PropisUkrResult) {
            this.PropisUkrResult = PropisUkrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXml", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlRequest() {
        }
        
        public GetXmlRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.GetXmlResult GetXmlResult;
        
        public GetXmlResponse() {
        }
        
        public GetXmlResponse(Morpher.WebService.V3.MorpherSoap.GetXmlResult GetXmlResult) {
            this.GetXmlResult = GetXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Propis", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.WebService.V3.MorpherSoap.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisRequest() {
        }
        
        public PropisRequest(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.WebService.V3.MorpherSoap.PropisResult PropisResult;
        
        public PropisResponse() {
        }
        
        public PropisResponse(Morpher.WebService.V3.MorpherSoap.PropisResult PropisResult) {
            this.PropisResult = PropisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Morpher.WebService.V3.MorpherSoap.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Morpher.WebService.V3.MorpherSoap.WebServiceSoap>, Morpher.WebService.V3.MorpherSoap.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAdjectives(Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest request) {
            return base.Channel.GetAdjectives(request);
        }
        
        public string[] GetAdjectives(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAdjectives(inValue);
            return retVal.GetAdjectivesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAdjectivesAsync(Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest request) {
            return base.Channel.GetAdjectivesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectivesResponse> GetAdjectivesAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAdjectivesRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAdjectivesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAdjectiveGenders(Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest request) {
            return base.Channel.GetAdjectiveGenders(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.AdjectiveGenders GetAdjectiveGenders(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAdjectiveGenders(inValue);
            return retVal.GetAdjectiveGendersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAdjectiveGendersAsync(Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest request) {
            return base.Channel.GetAdjectiveGendersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersResponse> GetAdjectiveGendersAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAdjectiveGendersRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAdjectiveGendersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.SubmitCorrection(Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest request) {
            return base.Channel.SubmitCorrection(request);
        }
        
        public void SubmitCorrection(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, Morpher.WebService.V3.MorpherSoap.GetXmlResult correction, string comment) {
            Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest inValue = new Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest();
            inValue.Credentials = Credentials;
            inValue.correction = correction;
            inValue.comment = comment;
            Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).SubmitCorrection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.SubmitCorrectionAsync(Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest request) {
            return base.Channel.SubmitCorrectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.SubmitCorrectionResponse> SubmitCorrectionAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, Morpher.WebService.V3.MorpherSoap.GetXmlResult correction, string comment) {
            Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest inValue = new Morpher.WebService.V3.MorpherSoap.SubmitCorrectionRequest();
            inValue.Credentials = Credentials;
            inValue.correction = correction;
            inValue.comment = comment;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).SubmitCorrectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAccountStatus(Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest request) {
            return base.Channel.GetAccountStatus(request);
        }
        
        public string GetAccountStatus(Morpher.WebService.V3.MorpherSoap.Credentials Credentials) {
            Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest();
            inValue.Credentials = Credentials;
            Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAccountStatus(inValue);
            return retVal.GetAccountStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetAccountStatusAsync(Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest request) {
            return base.Channel.GetAccountStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetAccountStatusResponse> GetAccountStatusAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials) {
            Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetAccountStatusRequest();
            inValue.Credentials = Credentials;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetAccountStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetDeclension(Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest request) {
            return base.Channel.GetDeclension(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.GetXmlResult GetDeclension(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetDeclension(inValue);
            return retVal.GetDeclensionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetDeclensionAsync(Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest request) {
            return base.Channel.GetDeclensionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetDeclensionResponse> GetDeclensionAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetDeclensionRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetDeclensionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetXmlUkr(Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest request) {
            return base.Channel.GetXmlUkr(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.GetXmlUkrResult GetXmlUkr(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetXmlUkr(inValue);
            return retVal.GetXmlUkrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetXmlUkrAsync(Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest request) {
            return base.Channel.GetXmlUkrAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlUkrResponse> GetXmlUkrAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetXmlUkrRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetXmlUkrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.PropisUkrResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.PropisUkr(Morpher.WebService.V3.MorpherSoap.PropisUkrRequest request) {
            return base.Channel.PropisUkr(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.PropisUkrResult PropisUkr(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            Morpher.WebService.V3.MorpherSoap.PropisUkrRequest inValue = new Morpher.WebService.V3.MorpherSoap.PropisUkrRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            Morpher.WebService.V3.MorpherSoap.PropisUkrResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).PropisUkr(inValue);
            return retVal.PropisUkrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisUkrResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.PropisUkrAsync(Morpher.WebService.V3.MorpherSoap.PropisUkrRequest request) {
            return base.Channel.PropisUkrAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisUkrResponse> PropisUkrAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            Morpher.WebService.V3.MorpherSoap.PropisUkrRequest inValue = new Morpher.WebService.V3.MorpherSoap.PropisUkrRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).PropisUkrAsync(inValue);
        }
        
        public int GetDailyQueryLimit() {
            return base.Channel.GetDailyQueryLimit();
        }
        
        public System.Threading.Tasks.Task<int> GetDailyQueryLimitAsync() {
            return base.Channel.GetDailyQueryLimitAsync();
        }
        
        public bool ValidateClientID(string clientID) {
            return base.Channel.ValidateClientID(clientID);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateClientIDAsync(string clientID) {
            return base.Channel.ValidateClientIDAsync(clientID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.GetXmlResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetXml(Morpher.WebService.V3.MorpherSoap.GetXmlRequest request) {
            return base.Channel.GetXml(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.GetXmlResult GetXml(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetXmlRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetXmlRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.WebService.V3.MorpherSoap.GetXmlResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetXml(inValue);
            return retVal.GetXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.GetXmlAsync(Morpher.WebService.V3.MorpherSoap.GetXmlRequest request) {
            return base.Channel.GetXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.GetXmlResponse> GetXmlAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, string s) {
            Morpher.WebService.V3.MorpherSoap.GetXmlRequest inValue = new Morpher.WebService.V3.MorpherSoap.GetXmlRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).GetXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.WebService.V3.MorpherSoap.PropisResponse Morpher.WebService.V3.MorpherSoap.WebServiceSoap.Propis(Morpher.WebService.V3.MorpherSoap.PropisRequest request) {
            return base.Channel.Propis(request);
        }
        
        public Morpher.WebService.V3.MorpherSoap.PropisResult Propis(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            Morpher.WebService.V3.MorpherSoap.PropisRequest inValue = new Morpher.WebService.V3.MorpherSoap.PropisRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            Morpher.WebService.V3.MorpherSoap.PropisResponse retVal = ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).Propis(inValue);
            return retVal.PropisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisResponse> Morpher.WebService.V3.MorpherSoap.WebServiceSoap.PropisAsync(Morpher.WebService.V3.MorpherSoap.PropisRequest request) {
            return base.Channel.PropisAsync(request);
        }
        
        public System.Threading.Tasks.Task<Morpher.WebService.V3.MorpherSoap.PropisResponse> PropisAsync(Morpher.WebService.V3.MorpherSoap.Credentials Credentials, uint n, string unit) {
            Morpher.WebService.V3.MorpherSoap.PropisRequest inValue = new Morpher.WebService.V3.MorpherSoap.PropisRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            return ((Morpher.WebService.V3.MorpherSoap.WebServiceSoap)(this)).PropisAsync(inValue);
        }
    }
}
