// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morpher.WebService.V3.Connected_Services.MorpherSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://morpher.ru/", ConfigurationName="MorpherSoap.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetAdjectivesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetAdjectivesResponse GetAdjectives(GetAdjectivesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectives", ReplyAction="*")]
        System.Threading.Tasks.Task<GetAdjectivesResponse> GetAdjectivesAsync(GetAdjectivesRequest request);
        
        // CODEGEN: Generating message contract since message GetAdjectiveGendersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectiveGenders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetAdjectiveGendersResponse GetAdjectiveGenders(GetAdjectiveGendersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAdjectiveGenders", ReplyAction="*")]
        System.Threading.Tasks.Task<GetAdjectiveGendersResponse> GetAdjectiveGendersAsync(GetAdjectiveGendersRequest request);
        
        // CODEGEN: Generating message contract since message SubmitCorrectionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/SubmitCorrection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SubmitCorrectionResponse SubmitCorrection(SubmitCorrectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/SubmitCorrection", ReplyAction="*")]
        System.Threading.Tasks.Task<SubmitCorrectionResponse> SubmitCorrectionAsync(SubmitCorrectionRequest request);
        
        // CODEGEN: Generating message contract since message GetAccountStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetAccountStatusResponse GetAccountStatus(GetAccountStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAccountStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<GetAccountStatusResponse> GetAccountStatusAsync(GetAccountStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetDeclensionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDeclension", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDeclensionResponse GetDeclension(GetDeclensionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDeclension", ReplyAction="*")]
        System.Threading.Tasks.Task<GetDeclensionResponse> GetDeclensionAsync(GetDeclensionRequest request);
        
        // CODEGEN: Generating message contract since message GetXmlUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXmlUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetXmlUkrResponse GetXmlUkr(GetXmlUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXmlUkr", ReplyAction="*")]
        System.Threading.Tasks.Task<GetXmlUkrResponse> GetXmlUkrAsync(GetXmlUkrRequest request);
        
        // CODEGEN: Generating message contract since message PropisUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/PropisUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PropisUkrResponse PropisUkr(PropisUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/PropisUkr", ReplyAction="*")]
        System.Threading.Tasks.Task<PropisUkrResponse> PropisUkrAsync(PropisUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDailyQueryLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDailyQueryLimit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDailyQueryLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDailyQueryLimitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/ValidateClientID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateClientID(string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/ValidateClientID", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidateClientIDAsync(string clientID);
        
        // CODEGEN: Generating message contract since message GetXmlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetXmlResponse GetXml(GetXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXml", ReplyAction="*")]
        System.Threading.Tasks.Task<GetXmlResponse> GetXmlAsync(GetXmlRequest request);
        
        // CODEGEN: Generating message contract since message PropisRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/Propis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PropisResponse Propis(PropisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/Propis", ReplyAction="*")]
        System.Threading.Tasks.Task<PropisResponse> PropisAsync(PropisRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Forms nField;
        
        private Forms unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Forms n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Forms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string иField;
        
        private string рField;
        
        private string дField;
        
        private string вField;
        
        private string тField;
        
        private string пField;
        
        private string поField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
                this.RaisePropertyChanged("И");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string В {
            get {
                return this.вField;
            }
            set {
                this.вField = value;
                this.RaisePropertyChanged("В");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Т {
            get {
                return this.тField;
            }
            set {
                this.тField = value;
                this.RaisePropertyChanged("Т");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string П {
            get {
                return this.пField;
            }
            set {
                this.пField = value;
                this.RaisePropertyChanged("П");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("П-о", Order=6)]
        public string По {
            get {
                return this.поField;
            }
            set {
                this.поField = value;
                this.RaisePropertyChanged("По");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlResult : Forms {
        
        private string родField;
        
        private Forms множественноеField;
        
        private string гдеField;
        
        private string кудаField;
        
        private string откудаField;
        
        private ФИО фИОField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string род {
            get {
                return this.родField;
            }
            set {
                this.родField = value;
                this.RaisePropertyChanged("род");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множественное {
            get {
                return this.множественноеField;
            }
            set {
                this.множественноеField = value;
                this.RaisePropertyChanged("множественное");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string где {
            get {
                return this.гдеField;
            }
            set {
                this.гдеField = value;
                this.RaisePropertyChanged("где");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string куда {
            get {
                return this.кудаField;
            }
            set {
                this.кудаField = value;
                this.RaisePropertyChanged("куда");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string откуда {
            get {
                return this.откудаField;
            }
            set {
                this.откудаField = value;
                this.RaisePropertyChanged("откуда");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
                this.RaisePropertyChanged("ФИО");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class ФИО : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string фField;
        
        private string иField;
        
        private string оField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ф {
            get {
                return this.фField;
            }
            set {
                this.фField = value;
                this.RaisePropertyChanged("Ф");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
                this.RaisePropertyChanged("И");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
                this.RaisePropertyChanged("О");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisUkrResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormsUkr nField;
        
        private FormsUkr unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormsUkr n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormsUkr unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlUkrResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class FormsUkr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string нField;
        
        private string рField;
        
        private string дField;
        
        private string зField;
        
        private string оField;
        
        private string мField;
        
        private string кField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Н {
            get {
                return this.нField;
            }
            set {
                this.нField = value;
                this.RaisePropertyChanged("Н");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string З {
            get {
                return this.зField;
            }
            set {
                this.зField = value;
                this.RaisePropertyChanged("З");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
                this.RaisePropertyChanged("О");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string М {
            get {
                return this.мField;
            }
            set {
                this.мField = value;
                this.RaisePropertyChanged("М");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string К {
            get {
                return this.кField;
            }
            set {
                this.кField = value;
                this.RaisePropertyChanged("К");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlUkrResult : FormsUkr {
        
        private string рідField;
        
        private Forms множинаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string рід {
            get {
                return this.рідField;
            }
            set {
                this.рідField = value;
                this.RaisePropertyChanged("рід");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множина {
            get {
                return this.множинаField;
            }
            set {
                this.множинаField = value;
                this.RaisePropertyChanged("множина");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class AdjectiveGenders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feminineField;
        
        private string neuterField;
        
        private string pluralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feminine {
            get {
                return this.feminineField;
            }
            set {
                this.feminineField = value;
                this.RaisePropertyChanged("feminine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string neuter {
            get {
                return this.neuterField;
            }
            set {
                this.neuterField = value;
                this.RaisePropertyChanged("neuter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string plural {
            get {
                return this.pluralField;
            }
            set {
                this.pluralField = value;
                this.RaisePropertyChanged("plural");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectives", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectivesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetAdjectivesRequest() {
        }
        
        public GetAdjectivesRequest(Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectivesResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectivesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string[] GetAdjectivesResult;
        
        public GetAdjectivesResponse() {
        }
        
        public GetAdjectivesResponse(string[] GetAdjectivesResult) {
            this.GetAdjectivesResult = GetAdjectivesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectiveGenders", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectiveGendersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetAdjectiveGendersRequest() {
        }
        
        public GetAdjectiveGendersRequest(Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAdjectiveGendersResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAdjectiveGendersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public AdjectiveGenders GetAdjectiveGendersResult;
        
        public GetAdjectiveGendersResponse() {
        }
        
        public GetAdjectiveGendersResponse(AdjectiveGenders GetAdjectiveGendersResult) {
            this.GetAdjectiveGendersResult = GetAdjectiveGendersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrection", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class SubmitCorrectionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public GetXmlResult correction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string comment;
        
        public SubmitCorrectionRequest() {
        }
        
        public SubmitCorrectionRequest(Credentials Credentials, GetXmlResult correction, string comment) {
            this.Credentials = Credentials;
            this.correction = correction;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrectionResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class SubmitCorrectionResponse {
        
        public SubmitCorrectionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatus", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAccountStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        public GetAccountStatusRequest() {
        }
        
        public GetAccountStatusRequest(Credentials Credentials) {
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatusResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetAccountStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string GetAccountStatusResult;
        
        public GetAccountStatusResponse() {
        }
        
        public GetAccountStatusResponse(string GetAccountStatusResult) {
            this.GetAccountStatusResult = GetAccountStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeclension", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetDeclensionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetDeclensionRequest() {
        }
        
        public GetDeclensionRequest(Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeclensionResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetDeclensionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public GetXmlResult GetDeclensionResult;
        
        public GetDeclensionResponse() {
        }
        
        public GetDeclensionResponse(GetXmlResult GetDeclensionResult) {
            this.GetDeclensionResult = GetDeclensionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlUkrRequest() {
        }
        
        public GetXmlUkrRequest(Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public GetXmlUkrResult GetXmlUkrResult;
        
        public GetXmlUkrResponse() {
        }
        
        public GetXmlUkrResponse(GetXmlUkrResult GetXmlUkrResult) {
            this.GetXmlUkrResult = GetXmlUkrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisUkrRequest() {
        }
        
        public PropisUkrRequest(Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public PropisUkrResult PropisUkrResult;
        
        public PropisUkrResponse() {
        }
        
        public PropisUkrResponse(PropisUkrResult PropisUkrResult) {
            this.PropisUkrResult = PropisUkrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXml", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlRequest() {
        }
        
        public GetXmlRequest(Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class GetXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public GetXmlResult GetXmlResult;
        
        public GetXmlResponse() {
        }
        
        public GetXmlResponse(GetXmlResult GetXmlResult) {
            this.GetXmlResult = GetXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Propis", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisRequest() {
        }
        
        public PropisRequest(Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    public partial class PropisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public PropisResult PropisResult;
        
        public PropisResponse() {
        }
        
        public PropisResponse(PropisResult PropisResult) {
            this.PropisResult = PropisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceSoap>, WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetAdjectivesResponse WebServiceSoap.GetAdjectives(GetAdjectivesRequest request) {
            return base.Channel.GetAdjectives(request);
        }
        
        public string[] GetAdjectives(Credentials Credentials, string s) {
            GetAdjectivesRequest inValue = new GetAdjectivesRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            GetAdjectivesResponse retVal = ((WebServiceSoap)(this)).GetAdjectives(inValue);
            return retVal.GetAdjectivesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetAdjectivesResponse> WebServiceSoap.GetAdjectivesAsync(GetAdjectivesRequest request) {
            return base.Channel.GetAdjectivesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetAdjectivesResponse> GetAdjectivesAsync(Credentials Credentials, string s) {
            GetAdjectivesRequest inValue = new GetAdjectivesRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((WebServiceSoap)(this)).GetAdjectivesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetAdjectiveGendersResponse WebServiceSoap.GetAdjectiveGenders(GetAdjectiveGendersRequest request) {
            return base.Channel.GetAdjectiveGenders(request);
        }
        
        public AdjectiveGenders GetAdjectiveGenders(Credentials Credentials, string s) {
            GetAdjectiveGendersRequest inValue = new GetAdjectiveGendersRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            GetAdjectiveGendersResponse retVal = ((WebServiceSoap)(this)).GetAdjectiveGenders(inValue);
            return retVal.GetAdjectiveGendersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetAdjectiveGendersResponse> WebServiceSoap.GetAdjectiveGendersAsync(GetAdjectiveGendersRequest request) {
            return base.Channel.GetAdjectiveGendersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetAdjectiveGendersResponse> GetAdjectiveGendersAsync(Credentials Credentials, string s) {
            GetAdjectiveGendersRequest inValue = new GetAdjectiveGendersRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((WebServiceSoap)(this)).GetAdjectiveGendersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubmitCorrectionResponse WebServiceSoap.SubmitCorrection(SubmitCorrectionRequest request) {
            return base.Channel.SubmitCorrection(request);
        }
        
        public void SubmitCorrection(Credentials Credentials, GetXmlResult correction, string comment) {
            SubmitCorrectionRequest inValue = new SubmitCorrectionRequest();
            inValue.Credentials = Credentials;
            inValue.correction = correction;
            inValue.comment = comment;
            SubmitCorrectionResponse retVal = ((WebServiceSoap)(this)).SubmitCorrection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubmitCorrectionResponse> WebServiceSoap.SubmitCorrectionAsync(SubmitCorrectionRequest request) {
            return base.Channel.SubmitCorrectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SubmitCorrectionResponse> SubmitCorrectionAsync(Credentials Credentials, GetXmlResult correction, string comment) {
            SubmitCorrectionRequest inValue = new SubmitCorrectionRequest();
            inValue.Credentials = Credentials;
            inValue.correction = correction;
            inValue.comment = comment;
            return ((WebServiceSoap)(this)).SubmitCorrectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetAccountStatusResponse WebServiceSoap.GetAccountStatus(GetAccountStatusRequest request) {
            return base.Channel.GetAccountStatus(request);
        }
        
        public string GetAccountStatus(Credentials Credentials) {
            GetAccountStatusRequest inValue = new GetAccountStatusRequest();
            inValue.Credentials = Credentials;
            GetAccountStatusResponse retVal = ((WebServiceSoap)(this)).GetAccountStatus(inValue);
            return retVal.GetAccountStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetAccountStatusResponse> WebServiceSoap.GetAccountStatusAsync(GetAccountStatusRequest request) {
            return base.Channel.GetAccountStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetAccountStatusResponse> GetAccountStatusAsync(Credentials Credentials) {
            GetAccountStatusRequest inValue = new GetAccountStatusRequest();
            inValue.Credentials = Credentials;
            return ((WebServiceSoap)(this)).GetAccountStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDeclensionResponse WebServiceSoap.GetDeclension(GetDeclensionRequest request) {
            return base.Channel.GetDeclension(request);
        }
        
        public GetXmlResult GetDeclension(Credentials Credentials, string s) {
            GetDeclensionRequest inValue = new GetDeclensionRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            GetDeclensionResponse retVal = ((WebServiceSoap)(this)).GetDeclension(inValue);
            return retVal.GetDeclensionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetDeclensionResponse> WebServiceSoap.GetDeclensionAsync(GetDeclensionRequest request) {
            return base.Channel.GetDeclensionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetDeclensionResponse> GetDeclensionAsync(Credentials Credentials, string s) {
            GetDeclensionRequest inValue = new GetDeclensionRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((WebServiceSoap)(this)).GetDeclensionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetXmlUkrResponse WebServiceSoap.GetXmlUkr(GetXmlUkrRequest request) {
            return base.Channel.GetXmlUkr(request);
        }
        
        public GetXmlUkrResult GetXmlUkr(Credentials Credentials, string s) {
            GetXmlUkrRequest inValue = new GetXmlUkrRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            GetXmlUkrResponse retVal = ((WebServiceSoap)(this)).GetXmlUkr(inValue);
            return retVal.GetXmlUkrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetXmlUkrResponse> WebServiceSoap.GetXmlUkrAsync(GetXmlUkrRequest request) {
            return base.Channel.GetXmlUkrAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetXmlUkrResponse> GetXmlUkrAsync(Credentials Credentials, string s) {
            GetXmlUkrRequest inValue = new GetXmlUkrRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((WebServiceSoap)(this)).GetXmlUkrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PropisUkrResponse WebServiceSoap.PropisUkr(PropisUkrRequest request) {
            return base.Channel.PropisUkr(request);
        }
        
        public PropisUkrResult PropisUkr(Credentials Credentials, uint n, string unit) {
            PropisUkrRequest inValue = new PropisUkrRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            PropisUkrResponse retVal = ((WebServiceSoap)(this)).PropisUkr(inValue);
            return retVal.PropisUkrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PropisUkrResponse> WebServiceSoap.PropisUkrAsync(PropisUkrRequest request) {
            return base.Channel.PropisUkrAsync(request);
        }
        
        public System.Threading.Tasks.Task<PropisUkrResponse> PropisUkrAsync(Credentials Credentials, uint n, string unit) {
            PropisUkrRequest inValue = new PropisUkrRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            return ((WebServiceSoap)(this)).PropisUkrAsync(inValue);
        }
        
        public int GetDailyQueryLimit() {
            return base.Channel.GetDailyQueryLimit();
        }
        
        public System.Threading.Tasks.Task<int> GetDailyQueryLimitAsync() {
            return base.Channel.GetDailyQueryLimitAsync();
        }
        
        public bool ValidateClientID(string clientID) {
            return base.Channel.ValidateClientID(clientID);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateClientIDAsync(string clientID) {
            return base.Channel.ValidateClientIDAsync(clientID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetXmlResponse WebServiceSoap.GetXml(GetXmlRequest request) {
            return base.Channel.GetXml(request);
        }
        
        public GetXmlResult GetXml(Credentials Credentials, string s) {
            GetXmlRequest inValue = new GetXmlRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            GetXmlResponse retVal = ((WebServiceSoap)(this)).GetXml(inValue);
            return retVal.GetXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetXmlResponse> WebServiceSoap.GetXmlAsync(GetXmlRequest request) {
            return base.Channel.GetXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetXmlResponse> GetXmlAsync(Credentials Credentials, string s) {
            GetXmlRequest inValue = new GetXmlRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            return ((WebServiceSoap)(this)).GetXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PropisResponse WebServiceSoap.Propis(PropisRequest request) {
            return base.Channel.Propis(request);
        }
        
        public PropisResult Propis(Credentials Credentials, uint n, string unit) {
            PropisRequest inValue = new PropisRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            PropisResponse retVal = ((WebServiceSoap)(this)).Propis(inValue);
            return retVal.PropisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PropisResponse> WebServiceSoap.PropisAsync(PropisRequest request) {
            return base.Channel.PropisAsync(request);
        }
        
        public System.Threading.Tasks.Task<PropisResponse> PropisAsync(Credentials Credentials, uint n, string unit) {
            PropisRequest inValue = new PropisRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            return ((WebServiceSoap)(this)).PropisAsync(inValue);
        }
    }
}
